function ShowInstructions(win, white, black, xCenter, yCenter)
Screen('FillRect', win, black);
DrawFormattedText(win, ...
    ['Welcome!\n\n' ...
     'Fixate the red dot.\n' ...
     'You will hear two quick sounds.\n\n' ...
     'Press LEFT if the second sound is to the left of the first sound. \n' ...
     'Press RIGHT if the second sound is to the right of the first sound.\n\n' ...
     'Press any key to begin. (ESC to quit anytime)'], ...
     'center', 'center', white, 70);
Screen('Flip', win);
KbStrokeWait;
end