function ShowInstructions(win, white, black, xCenter, yCenter)
Screen('FillRect', win, black);
DrawFormattedText(win, ...
    ['Welcome!\n\n' ...
     'Fixate the center dot.\n' ...
     'A purple dot will mark LEFT or RIGHT during the yellow cue.\n' ...
     'During GREEN, you''ll hear two quick sounds.\n\n' ...
     'Press LEFT if the sounds end on the LEFT side,\n' ...
     'Press RIGHT if they end on the RIGHT side.\n\n' ...
     'Press any key to begin. (ESC to quit anytime)'], ...
     'center', 'center', white, 70);
Screen('Flip', win);
KbStrokeWait;
end